name: Deploy Frontend
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker login -u ${{ secrets.xt10101 }} -p ${{ secrets.5peWr-GE4DTsUg_ }}
      - run: docker build -t xt10101/react-test -f Dockerfile.dev .
      - run: docker run -e CI=true xt10101/react-test npm test
